name: py-substrate
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.4.13=h06a4308_1
  - certifi=2020.12.5=py38h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.0.1=py38h06a4308_0
  - python=3.8.8=hdb3f193_5
  - readline=8.1=h27cfd23_0
  - rope=0.18.0=py_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - apscheduler==3.7.0
    - base58==2.0.1
    - chardet==4.0.0
    - click==7.1.2
    - cytoolz==0.11.0
    - eth-hash==0.3.1
    - eth-typing==2.2.2
    - eth-utils==1.10.0
    - flask==1.1.2
    - idna==2.10
    - itsdangerous==1.1.0
    - jinja2==2.11.3
    - markupsafe==1.1.1
    - more-itertools==8.7.0
    - py-bip39-bindings==0.1.6
    - py-ed25519-bindings==0.1.2
    - py-sr25519-bindings==0.1.2
    - pycryptodome==3.10.1
    - pytz==2021.1
    - requests==2.25.1
    - scalecodec==0.10.87
    - six==1.16.0
    - substrate-interface==0.12.7
    - toolz==0.11.1
    - tzlocal==2.1
    - urllib3==1.26.4
    - websocket-client==0.58.0
    - werkzeug==1.0.1
    - xxhash==2.0.2
