[package]
name = "index-manager"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-http-server = "15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"
log = "0.4.0"
env_logger = "0.8.4"
tonic = "0.4" # Chain Reader Client
prost = "0.7" # Chain Reader Client
async-std = "1.9.0"
tokio = {version = "1.2.0", features = ["full"]} # Required by Tonic
futures = { version = "0.3.13", features = ["compat"] }
tokio-compat-02 = "0.2"
serde_yaml = "0.8"
anyhow = "1.0"
diesel = { version = "1.4.0", features = ["postgres"] }

# Massbit dependencies
ipfs-client = { path = "../../core/ipfs-client" }

manifest-reader = { path = "../manifest-reader" }
tokio02-spawn = { path = "../../core/tokio02-spawn" }
massbit-chain-substrate = { path = "../../core/chain/substrate"}
index-store = { path = "../../core/index-store" }

[build-dependencies]
tonic-build = "0.4" # Chain Reader Client

[dependencies.node-template-runtime]
git = "https://github.com/scs/substrate-api-client-test-node"
branch = "bump-to-polkadot-v0.9.2"

[dependencies.sp-runtime]
git = "https://github.com/paritytech/substrate.git"
branch = "master"
package = "sp-runtime"
default-features=false