[package]
name = "sum-storage-runtime-api"
version = "2.0.0"
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
sp-api = { version = '2.0.0', default-features = false}
sp-std = { version = '2.0.0', default-features = false}
pallet-massbit = { path = '../../../pallets/massbit', default-features = false }
frame-system = { default-features = false, version = '2.0.1' }
frame-support = { default-features = false, version = '2.0.1' }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = [
	"sp-api/std",
	"sp-std/std",
	"pallet-massbit/std",
	"frame-support/std",
]
