[package]
name = "runtime-wasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
massbit = { path = "../../massbit" }
async-trait = "0.1.50"
atomic_refcell = "0.1.7"
ethabi = { git = "https://github.com/graphprotocol/ethabi.git", branch = "master" }
futures = "0.1.21"
hex = "0.4.3"
bs58 = "0.4.0"
runtime-derive = { path = "../derive" }
semver = "1.0.3"
lazy_static = "1.4"
uuid = { version = "0.8.1", features = ["v4"] }
strum = "0.21.0"
strum_macros = "0.21.1"
bytes = "1.0"
anyhow = "1.0"
wasmtime = "0.27.0"
defer = "0.1"
never = "0.1"
tiny-keccak = "1.5.0"